import type { Metadata } from "next";
import { Manrope, Work_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navBar";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Protfolio | Mayur Gotmare",
  description: "Generated by Mayur Gotmare",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} ${workSans.className} antialiased `}
      >
        <Navbar />
        {children}
        
      </body>
    </html>
  );
}

